//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anomaly
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public string AnomalyTypeCode { get; set; }
        public string ProofTypeCode { get; set; }
        public Nullable<decimal> HolderNbr { get; set; }
        public string AnomalyThemeCode { get; set; }
    
        public virtual AnomalyTheme AnomalyTheme { get; set; }
        public virtual AnomalyType AnomalyType { get; set; }
    }
}
