//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitizenCard
    {
        public string TaxIdNum { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdNumber { get; set; }
        public string DocNum { get; set; }
        public string SocialSecNum { get; set; }
        public string SnsNum { get; set; }
        public string CardCheckDigit { get; set; }
        public string DocCheckDigit { get; set; }
        public string FatherFirstName { get; set; }
        public string FatherLastName { get; set; }
        public string MotherFirstName { get; set; }
        public string MotherLastName { get; set; }
        public string Nationality { get; set; }
        public string CountryOfBirth { get; set; }
        public string Height { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Issuer { get; set; }
        public string IssuerDistrict { get; set; }
        public Nullable<System.DateTime> EmissionDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string CardVersion { get; set; }
        public string DocType { get; set; }
        public string TaxTypeId { get; set; }
        public string District { get; set; }
        public string DistrictDesc { get; set; }
        public string County { get; set; }
        public string CountyDesc { get; set; }
        public string Town { get; set; }
        public string TownDesc { get; set; }
        public string Locality { get; set; }
        public string PostalCode { get; set; }
        public string SubPostalCode { get; set; }
        public string PostalLocality { get; set; }
        public string AddressType { get; set; }
        public string Address { get; set; }
        public string AddressNum { get; set; }
        public string Floor { get; set; }
        public string Door { get; set; }
        public string Country { get; set; }
        public string Side { get; set; }
        public string Street { get; set; }
        public string StreetDesc { get; set; }
        public string StreetDesignation { get; set; }
        public string Building { get; set; }
        public string BuildingDesc { get; set; }
        public string FilePath { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<bool> IndPersonalDataRetrievedManually { get; set; }
        public Nullable<bool> IndAddressDataRetrievedManually { get; set; }
    }
}
