//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAProcessPhysicalContract
    {
        public string ID { get; set; }
        public long DAProcessSeqNbr { get; set; }
        public string StatusCode { get; set; }
    
        public virtual ContractPhysicalStatu ContractPhysicalStatu { get; set; }
        public virtual DAProcess DAProcess { get; set; }
    }
}
