//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAProcessDoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAProcessDoc()
        {
            this.DAProcessDocHistories = new HashSet<DAProcessDocHistory>();
            this.DAProcessSignatures = new HashSet<DAProcessSignature>();
        }
    
        public long SeqNbr { get; set; }
        public long DAProcessSeqNbr { get; set; }
        public string DocTypeCode { get; set; }
        public string Path { get; set; }
        public Nullable<int> Version { get; set; }
        public string DocStatusCode { get; set; }
        public string Status { get; set; }
        public string StatusDate { get; set; }
        public string StatusTime { get; set; }
        public string Motive { get; set; }
        public Nullable<bool> IndManualAttach { get; set; }
        public string AttachmentDate { get; set; }
        public string AttachmentTime { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public string ExternalDocID { get; set; }
        public string CustomerNbr { get; set; }
        public string Source { get; set; }
        public Nullable<int> NbrPages { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Order { get; set; }
        public bool Deleted { get; set; }
        public string ValidationTypeCode { get; set; }
        public string DigitalValidationCode { get; set; }
        public string PhysicalValidationCode { get; set; }
        public string BatchID { get; set; }
        public Nullable<bool> IsSignedPrimaryHolder { get; set; }
        public Nullable<bool> IsSignedSecondaryHolder { get; set; }
        public string ProofDocCode { get; set; }
        public Nullable<bool> CanAttach { get; set; }
        public Nullable<bool> SignatureRequired { get; set; }
        public Nullable<int> MinPages { get; set; }
        public Nullable<int> MaxPages { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public DAProcess DAProcess { get; set; }
        public DAProcessDocStatu DAProcessDocStatu { get; set; }
        public DocArchiveStatu DocArchiveStatu { get; set; }
        public ProofDoc ProofDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<DAProcessDocHistory> DAProcessDocHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<DAProcessSignature> DAProcessSignatures { get; set; }
    }
}
