//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAProcessWorkQueueHistory
    {
        public long SeqNbr { get; set; }
        public long DAProcessSeqNbr { get; set; }
        public string WorkQueueCode { get; set; }
        public System.DateTime AssignDate { get; set; }
        public Nullable<int> Delay { get; set; }
        public string Priority { get; set; }
        public string TreatmentUser { get; set; }
        public Nullable<System.DateTime> TreatmentBeginDate { get; set; }
        public Nullable<System.DateTime> TreatmentEndDate { get; set; }
        public string TransitionTypeCode { get; set; }
        public string TransitionUser { get; set; }
    
        public virtual DAProcess DAProcess { get; set; }
        public virtual TransitionType TransitionType { get; set; }
        public virtual WorkQueue WorkQueue { get; set; }
    }
}
