//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAProcessAnomaly
    {
        public long SeqNbr { get; set; }
        public string BizProcNbr { get; set; }
        public string AnomalyCode { get; set; }
        public Nullable<System.DateTime> AnomalyDateTime { get; set; }
        public Nullable<bool> Resolved { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string ResolvedUser { get; set; }
        public string CreationUser { get; set; }
    }
}
