//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAProcess()
        {
            this.ContractBreaches = new HashSet<ContractBreach>();
            this.DAProcess1 = new HashSet<DAProcess>();
            this.DAProcessHolders = new HashSet<DAProcessHolder>();
            this.DAProcessDocs = new HashSet<DAProcessDoc>();
            this.DAProcessOperations = new HashSet<DAProcessOperation>();
            this.DAProcessPhysicalContracts = new HashSet<DAProcessPhysicalContract>();
            this.DAProcessSignatures = new HashSet<DAProcessSignature>();
            this.DAProcessWorkQueueHistories = new HashSet<DAProcessWorkQueueHistory>();
            this.DeclarationRequests = new HashSet<DeclarationRequest>();
            this.InsuranceVoids = new HashSet<InsuranceVoid>();
            this.DigitalRequests = new HashSet<DigitalRequest>();
        }
    
        public long SeqNbr { get; set; }
        public string ProductCode { get; set; }
        public string BizProcCode { get; set; }
        public string BizProcNbr { get; set; }
        public string CBMCode { get; set; }
        public string Status { get; set; }
        public string Motive { get; set; }
        public string BranchCode { get; set; }
        public string StatusDate { get; set; }
        public string StatusTime { get; set; }
        public Nullable<int> NbrMandatoryDoc { get; set; }
        public string User { get; set; }
        public string PhysicalProcNbr { get; set; }
        public string ValidationTypeCode { get; set; }
        public string DigitalValidationCode { get; set; }
        public string PhysicalValidationCode { get; set; }
        public bool Lock { get; set; }
        public bool UserLock { get; set; }
        public string CreationDate { get; set; }
        public string CreationTime { get; set; }
        public string CreationUser { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNbr { get; set; }
        public string ContractNbr { get; set; }
        public string ValidationRuleset { get; set; }
        public string SaleProcessSeqNbr { get; set; }
        public bool IsSimplified { get; set; }
        public Nullable<bool> CentralStatus { get; set; }
        public string OPC { get; set; }
        public Nullable<bool> Transit { get; set; }
        public string EntryChannel { get; set; }
        public Nullable<long> AssociatedDAProcessSeqNbr { get; set; }
        public string ContactChannel { get; set; }
        public Nullable<bool> IndValidatedContract { get; set; }
        public string StatusUser { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ContractBreach> ContractBreaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<DAProcess> DAProcess1 { get; set; }
        public  DAProcess DAProcess2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<DAProcessHolder> DAProcessHolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<DAProcessDoc> DAProcessDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<DAProcessOperation> DAProcessOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<DAProcessPhysicalContract> DAProcessPhysicalContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<DAProcessSignature> DAProcessSignatures { get; set; }
        public  DAProcessWorkQueue DAProcessWorkQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<DAProcessWorkQueueHistory> DAProcessWorkQueueHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<DeclarationRequest> DeclarationRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<InsuranceVoid> InsuranceVoids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<DigitalRequest> DigitalRequests { get; set; }
    }
}
