//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DigitalRequest()
        {
            this.DAProcesses = new HashSet<DAProcess>();
        }
    
        public long SeqNbr { get; set; }
        public string Id { get; set; }
        public string Subject { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public System.DateTime Date { get; set; }
        public string ContentText { get; set; }
        public string ContentHTML { get; set; }
        public string BizProcessTypeCode { get; set; }
        public string User { get; set; }
        public bool UserLock { get; set; }
        public string Status { get; set; }
        public string CustomerNbr { get; set; }
        public string ContractNbr { get; set; }
    
        public virtual BizProcessType BizProcessType { get; set; }
        public virtual DigitalRequestStatu DigitalRequestStatu { get; set; }
        public virtual DigitalRequestWorkQueue DigitalRequestWorkQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAProcess> DAProcesses { get; set; }
    }
}
