//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmulatorData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmulatorData()
        {
            this.EmulatorRequestFields = new HashSet<EmulatorRequestField>();
            this.EmulatorResponseFields = new HashSet<EmulatorResponseField>();
        }
    
        public int ID { get; set; }
        public string MethodName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Delay { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
        public bool IsError { get; set; }
        public string Message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmulatorRequestField> EmulatorRequestFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmulatorResponseField> EmulatorResponseFields { get; set; }
    }
}
