//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETMRuntimeEntities : DbContext
    {
        public ETMRuntimeEntities()
            : base("name=ETMRuntimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TJ_Branch> TJ_Branch { get; set; }
        public virtual DbSet<TJ_WS> TJ_WS { get; set; }
        public virtual DbSet<Total_Branch> Total_Branch { get; set; }
        public virtual DbSet<WSRequest> WSRequests { get; set; }
        public virtual DbSet<HostRequest> HostRequests { get; set; }
        public virtual DbSet<TJSeqNbr> TJSeqNbrs { get; set; }
    }
}
