//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostRequest
    {
        public Nullable<decimal> AppSeqNbr { get; set; }
        public string DtRequest { get; set; }
        public string Request { get; set; }
    }
}
