//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceVoid
    {
        public long SeqNbr { get; set; }
        public long DAProcessSeqNbr { get; set; }
        public string InsuranceCode { get; set; }
        public string MotiveCode { get; set; }
        public string ActionCode { get; set; }
        public bool Processed { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public bool IsOutboundCampaign { get; set; }
        public string InsuranceProduct { get; set; }
    
        public virtual DAProcess DAProcess { get; set; }
        public virtual InsuranceProduct InsuranceProduct1 { get; set; }
    }
}
