//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualProcessVolumeReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManualProcessVolumeReg()
        {
            this.ManualProcessVolumeRegHistories = new HashSet<ManualProcessVolumeRegHistory>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string UserName { get; set; }
        public string ManualProcessType { get; set; }
        public Nullable<int> Volume { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualProcessVolumeRegHistory> ManualProcessVolumeRegHistories { get; set; }
    }
}
