//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualProcessVolumeRegHistory
    {
        public long ID { get; set; }
        public int ManualProcessID { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string RecordUser { get; set; }
        public string ManualProcessType { get; set; }
        public int Volume { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUser { get; set; }
    
        public virtual ManualProcessVolumeReg ManualProcessVolumeReg { get; set; }
    }
}
