//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProofType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProofType()
        {
            this.ProofTypeBizProcessTypes = new HashSet<ProofTypeBizProcessType>();
            this.ProofTypeDocs = new HashSet<ProofTypeDoc>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IndMandatorySimplified { get; set; }
        public Nullable<bool> IndMandatoryComplete { get; set; }
        public Nullable<int> NbrDaysAttachAfterArchive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProofTypeBizProcessType> ProofTypeBizProcessTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProofTypeDoc> ProofTypeDocs { get; set; }
    }
}
