//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal
    {
        public string ProposalNbr { get; set; }
        public string IBAN { get; set; }
        public string BIC_SWIFT { get; set; }
        public string AccountDate { get; set; }
        public string AccountOwnershipCode { get; set; }
        public string OPCCode { get; set; }
        public string OPCName { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<decimal> TAN { get; set; }
        public Nullable<decimal> TAEG { get; set; }
        public Nullable<bool> WithInsurance { get; set; }
        public Nullable<decimal> MinAmount { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<bool> BankCardDataAutoCollected { get; set; }
        public Nullable<bool> Adhesion { get; set; }
        public string InsuranceCode { get; set; }
        public string InsuranceDesc { get; set; }
        public Nullable<bool> Refusal { get; set; }
        public Nullable<bool> HasProvisionalCardNbr { get; set; }
    
        public virtual AccountOwnership AccountOwnership { get; set; }
    }
}
