//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulationParam
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public int Period { get; set; }
        public decimal Plaflond { get; set; }
        public decimal MonthlyFee { get; set; }
        public decimal FinalFee { get; set; }
        public decimal TAN { get; set; }
        public decimal TAEG { get; set; }
        public decimal MTICWithISUC { get; set; }
        public decimal MTICWithoutISUC { get; set; }
        public decimal FirstMonthlyFee { get; set; }
        public decimal InsuranceFee { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal OpenningFee { get; set; }
        public decimal StudyFee { get; set; }
        public decimal RequestedAmountPlusInsurance { get; set; }
        public bool HasInsurance { get; set; }
        public bool IsDefault { get; set; }
        public string SimulationTypeCode { get; set; }
    
        public virtual SimulationType SimulationType { get; set; }
    }
}
