//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJ_Branch
    {
        public decimal SeqNbr { get; set; }
        public string UserName { get; set; }
        public string Authorizer { get; set; }
        public string ProcDate { get; set; }
        public string ProcTime { get; set; }
        public string WorkDate { get; set; }
        public string Channel { get; set; }
        public string Institution { get; set; }
        public string Branch { get; set; }
        public string TxnCode { get; set; }
        public string TxnName { get; set; }
        public string Status { get; set; }
        public string RevStatus { get; set; }
        public Nullable<decimal> RevSeqNbr { get; set; }
        public string AcctNbr { get; set; }
        public Nullable<decimal> TxnAmount { get; set; }
        public string Currency { get; set; }
        public string DocNbr { get; set; }
        public string HostSeqNbr { get; set; }
        public string HostLineStatus { get; set; }
        public string HostResult { get; set; }
        public string HostMsg { get; set; }
        public string UserMsg { get; set; }
        public Nullable<bool> Regularize { get; set; }
        public string SysError { get; set; }
        public Nullable<bool> Reversible { get; set; }
        public Nullable<bool> ReprintAllowed { get; set; }
        public Nullable<bool> ReprintPartialAllowed { get; set; }
        public Nullable<int> PrintFormCount { get; set; }
        public string Workstation { get; set; }
        public string TxnDetail { get; set; }
    }
}
