//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Total_Branch
    {
        public string Name { get; set; }
        public string WorkDate { get; set; }
        public string User { get; set; }
        public string Channel { get; set; }
        public string InstitutionCode { get; set; }
        public string EnterpriseUnit { get; set; }
        public string Currency { get; set; }
        public decimal TotalValue { get; set; }
        public decimal Counter { get; set; }
    }
}
