//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFilter
    {
        public long SeqNbr { get; set; }
        public string Name { get; set; }
        public string FilterUser { get; set; }
        public string FilterTypeCode { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ProductCode { get; set; }
        public string Channel { get; set; }
        public string ContactChannel { get; set; }
        public string BranchCode { get; set; }
        public string WorkQueueCode { get; set; }
        public string User { get; set; }
        public bool ActiveSession { get; set; }
        public bool Default { get; set; }
    
        public virtual FilterType FilterType { get; set; }
    }
}
