//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSRequest
    {
        public string UserID { get; set; }
        public decimal ExternalSeqNbr { get; set; }
        public Nullable<decimal> InternalSeqNbr { get; set; }
        public Nullable<decimal> TJSeqNbr { get; set; }
        public Nullable<decimal> InstanceID { get; set; }
        public string DtRequest { get; set; }
        public string Response { get; set; }
    }
}
